<?php

$permission['dashboard.php']='can_view_dashboard';
$permission['customers.php']='can_view_customer_list';
$permission['create_customers.php']='can_create_customer';
$permission['edit_customers.php']='can_edit_customer';
$permission['view_customers.php']='can_view_customer';
$permission['delete_customers.php']='can_delete_customer';
$permission['diagrams.php']='can_view_diagrams_list';
$permission['create_diagrams.php']='can_create_diagrams';
$permission['edit_diagrams.php']='can_edit_diagrams';
$permission['view_diagrams.php']='can_view_diagrams';
$permission['delete_diagrams.php']='can_delete_diagrams';
$permission['create_route_card.php']='can_create_route_card';
$permission['view_route_card.php']='can_view_route_card';
$permission['edit_route_card.php']='can_edit_route_card';
$permission['delete_route_card.php']='can_delete_route_card';
$permission['route_card_list.php']='can_view_route_card_list';
$permission['create_employee.php']='can_create_employee';
$permission['view_employee.php']='can_view_employee';
$permission['edit_employee.php']='can_edit_employee';
$permission['delete_employee.php']='can_delete_employee';
$permission['view_employee_list.php']='can_view_employee_list';
$permission['create_final_inspection_report.php']='can_create_final_inspection_report';
$permission['edit_final_inspection_report.php']='can_edit_final_inspection_report';
$permission['view_final_inspection_report.php']='can_view_final_inspection_report';
$permission['delete_final_inspection_report.php']='can_delete_final_inspection_report';
$permission['view_final_inspection_report_list.php']='can_view_final_inspection_report_list';
$permission['my_account.php']='can_view_my_account_details';
$permission['download_customers.php']='can_view_customer';
$permission['download_diagrams.php']='can_view_diagrams';
$permission['download_route_card.php']='can_view_route_card_list';
$permission['download_employee.php']='can_view_employee_list';
$permission['download_route_card_single.php']='can_view_route_card';

?>